### PR TITLE
FIX Add carousel accessibility requirements

### PR DESCRIPTION
**Pull request by sachajudd**
Relies on https://github.com/silverstripe/bambusa-theme/pull/11
For more information on issues see,
https://github.com/silverstripe/cwp-watea-theme/issues/86
https://github.com/silverstripe/cwp-watea-theme/issues/85
https://github.com/silverstripe/cwp-watea-theme/issues/84
https://github.com/silverstripe/cwp-watea-theme/issues/83

Reference: https://github.com/silverstripe/bambusa-theme/issues/2 https://github.com/silverstripeltd/open-sourcerers/issues/101#issuecomment-512622412

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
# With the PR
image

# Without the PR
image

The slide indicator look different now. Is that on purpose?

There's not any outline around the slide indicator and the pause/play button, so it's hard to figure which one has the focus when using the keyboard to navigate.

The pause/play button has very poor colour contrast now.

Am I missing something here?

**Comment by sachajudd** [comment]
@maxime-rainville this PR relies on  silverstripe/bambusa-theme#11 did you test it with that?

**Comment by maxime-rainville** [comment]
That's explains things. I'll have another go at it.

**Comment by sachajudd** [comment]
Just a note for myself to port over some carousel.js changes I made here:
https://github.com/silverstripe/cwp-watea-theme/pull/95 either in a separate PR or after a review.

**Review by maxime-rainville — APPROVED** [review]

**Pull request merged**
