### PR TITLE
NEW CMS Analytics

### PR DESCRIPTION
**Pull request by chillu**
Not using Sam's tagmanager module because it doesn't apply in the CMS,
and there's no straightforward way to add this.

Since this only applies in the CMS, I don't expect it to collide
with any custom Google Analytics setup through the tagmanager module on the website itself.
I'm planning to set up the same Tracking ID there, but via the module (in the master prod database)

### CODE REVIEW

**Comment by chillu** [comment]
I've configured the env constant in https://platform.silverstripe.com/naut/project/sscom2/environment/prod/configuration, but haven't deployed yet.

Configured GA in the frontend via http://bambusad-prod.sites.silverstripe.com/admin/tagmanager/SilverStripe-TagManager-Model-Snippet/EditForm/field/SilverStripe-TagManager-Model-Snippet/item/7/edit, but also not "deployed" yet (not using new content snapshot)

**Review by dnsl48 — APPROVED** [review]
LGTM

**Comment by dnsl48** [comment]
Could potentially rename into `LeftAndMainGAExtension` or something alike, but works as is too.

**Comment by chillu** [comment]
Thanks Serge!

**Comment by chillu** [comment]
> I've configured the env constant in https://platform.silverstripe.com/naut/project/sscom2/environment/prod/configuration

That was a mistake, it doesn't need to be on ss.com - this is about the Bambusa demo itself. Deployed through https://platform.silverstripe.com/naut/project/solution/environment/prod/overview/deployment/77076, but relies on the new content snapshot being loaded

**Comment by sminnee** [comment]
From the looks of things this has taken the form of "Add GTM to LeftAndMain and we'll do the rest in the GTM UI?"

Keen to hear how it all works out. I'll look into improving silverstripe-tagmanager On A Future Hackday(tm).

**Comment by chillu** [comment]
> From the looks of things this has taken the form of "Add GTM to LeftAndMain and we'll do the rest in the GTM UI?"

Not really, this just adds GA which is done via `googletagmanager.com` these days apparently :D

**Pull request merged**
