### PR TITLE
DOC Add some doc for the community

### PR DESCRIPTION
**Pull request by maxime-rainville**
Add some doc for the community so members of the community can understand what this repo is for.

# Parent issue
* https://github.com/silverstripeltd/open-sourcerers/issues/66

### CODE REVIEW

**Review by dnsl48 — APPROVED** [review]
LGTM

**Comment by maxime-rainville** [comment]
I'm not sure if we wanted more technical doc for internal stake holders. Let me know if we need this.

**Comment by dnsl48** [comment]
We have separate documentation for docker setup. Everything else seems to be more or less same to a generic SilverStripe project. On the other hand, we can add more documentation when we add more functionality wherever it feels necessary. At this point I'm not exactly sure what else we can document in here.

**Comment by maxime-rainville** [comment]
Cool ... I'm calling this done and merging.

**Pull request merged**
