### PR TITLE
ENH / Xenial, add Travis ENV vars to docker image 

### PR DESCRIPTION
**Pull request by dnsl48**
- Upgrade Travis distro to Xenial
- Add build info to the docker image (for passing to Raygun)

The point of adding the TravisCI environment variables to the docker image is so those propagate to Raygun logs to facilitate later debugging.

### CODE REVIEW

**Comment by dnsl48** [comment]
The point of adding the TravisCI environment variables to the docker image is so those propagate to Raygun logs for later debugging purposes.

**Review by chillu — CHANGES_REQUESTED** [review]
As discussed yesterday, I don't think ENV vars are passed through to Apache and PHP automatically, and might not show up in Raygun metadata. Happy to be proven wrong though :)

**Comment by dnsl48** [comment]
That's right, my mistake. Only `$_SERVER` ends up being sent and not `$_ENV` https://github.com/MindscapeHQ/raygun4php/blob/master/src/Raygun4php/RaygunRequestMessage.php#L51

**Comment by dnsl48** [comment]
@chillu Added custom `Bambusa\Logging\RaygunHandler` implementation. That appears to be the easiest way.

**Review by chillu — APPROVED** [review]

**Comment by chillu** [comment]
Sweet, I can see the env vars on https://app.raygun.com/crashreporting/1po60pm/errors/3803803708?dateFrom=2019-07-22T05%3A16%3A46.000Z&dateTo=2019-07-29T05%3A16%3A46.000Z#48658312265

**Pull request merged**
