### PR TITLE
MNT Upgrade to CMS 4.7.2

### PR DESCRIPTION
**Pull request by maxime-rainville**
Fixes https://github.com/silverstripeltd/product-issues/issues/347

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
A few deps are going from tagged versions to .x-dev next-minor dev branches, is this intentional?  Seems a bit risky?

e.g. from "version": "4.5.0",
to "version": "4.x-dev",

**Comment by maxime-rainville** [comment]
That should take care of it.

**Comment by emteknetnz** [comment]
Looks like it downgraded instead of upgrading :-)

image

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Looks like something didn't quite go right with the upgrade because it downgraded.  Perhaps try `^2.7` without the `@stable`?

**Comment by maxime-rainville** [comment]
> Looks like something didn't quite go right with the upgrade because it downgraded. Perhaps try `^2.7` without the `@stable`?

When I tried that, it was installing the dev dependencies.

**Comment by maxime-rainville** [comment]
`silverstripe/recipe-content-blocks` 2.7.0 requires `cms` 4.7.0. The only version of `recipe-cms` that ships with `cms` is 4.7.0. That will also forces the installation `admin` 1.7.0.

Our combination of recipes with strict constraints probably makes int very difficult for composer to find a combination of installable versions. That's probably why we ended up with with dev dependencies in the first place.

**Comment by emteknetnz** [comment]
> When I tried that, it was installing the dev dependencies.

That ... is strange.  composer.json has
```
    "prefer-stable": true,
    "minimum-stability": "dev"
```
So it should just use tagged versions when you specify `^2(.7)`

>> silverstripe/recipe-content-blocks 2.7.0 requires cms 4.7.0.

Yeah that's unfortunate ... https://github.com/silverstripe/recipe-content-blocks/commit/f4c86bf5b4c9995eb32246a07be80082a00b0c1d (tag 2.7.0) ... looks like a cow thing ... seems we should really be releasing more recent versions of recipe-content-blocks that are just updates to composer.json.  Anyway that's for another day ...

I'm kind of surprised though that it's using the recipe-content-blocks versions given the recipe-cms versions are much more recent https://github.com/silverstripe/recipe-cms/commit/38de22ed4b48aefd4f65d755d3e71f408ce4865d (tag 4.7.2)

Both recipe-cms and recipe-content blocks are at the same level within [composer.json](https://github.com/silverstripe/bambusa-installer/blob/master/composer.json#L9)

It's probably worth updating everything in  composer.json to `^4` style to try and get the latest tagged stable version, some stuff just [looks wrong](https://github.com/silverstripe/bambusa-installer/blob/master/composer.json#L26)

**Comment by Cheddam** [comment]
`silverstripe/recipe-content-blocks` is part of the CWP release, so there'll be a `2.7.1` tag in a couple of weeks. Based on this requirement, I think we should be tying Bambusa updates to CWP releases, rather than Core ones.

**Comment by brynwhyman** [comment]
I don't think this is required any more. The current composer.json is pretty future-proof (currently creates a 4.8 project):
`"silverstripe/recipe-cms": "^4.7",`
`"silverstripe/recipe-content-blocks": "^2.3",`

**Pull request closed without merging**
